name: cse587-inference
channels:
  - defaults
dependencies:
  - python=3.12
  - pip=24.0
  - pip:
      - ipython==8.18.1
      - typed-argument-parser==1.10.1
      - numpy==1.26.4
      - datasets==3.2.0
      - scikit-learn==1.6.0
      - matplotlib==3.10.0
