### model
model_name_or_path: {model_name}
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: {dataset_name}
template: llama3
cutoff_len: 512
max_samples: 1000000000 # no limit
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: {output_dir}
logging_steps: 10
save_steps: 1000000000 # never save
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: {per_device_train_batch_size}
gradient_accumulation_steps: {gradient_accumulation_steps}
learning_rate: {learning_rate}
num_train_epochs: 1.0
lr_scheduler_type: linear  # cosine
warmup_ratio: 0.5
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
optim: adamw_torch
